# Generated by Django 4.2.7 on 2025-09-27 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], max_length=10)),
                ('planting_season', models.CharField(choices=[('spring', 'Primavera'), ('summer', 'Verano'), ('autumn', 'Otoño'), ('winter', 'Invierno'), ('all_year', 'Todo el año')], max_length=20)),
                ('harvest_time_days', models.PositiveIntegerField(help_text='Días desde siembra hasta cosecha')),
                ('space_required', models.FloatField(help_text='Espacio requerido en metros cuadrados')),
                ('water_frequency', models.PositiveIntegerField(help_text='Frecuencia de riego en días')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('size_m2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('soil_type', models.CharField(choices=[('sandy', 'Arenoso'), ('clay', 'Arcilloso'), ('loamy', 'Franco'), ('rocky', 'Rocoso')], max_length=20)),
                ('sun_exposure', models.CharField(choices=[('full_sun', 'Sol directo'), ('partial_sun', 'Sol parcial'), ('shade', 'Sombra')], max_length=20)),
                ('has_irrigation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CultivationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('active', 'Activo'), ('completed', 'Completado'), ('failed', 'Fallido')], default='planned', max_length=20)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.plant')),
            ],
        ),
    ]
